main_app/urls.py
from django.urls import path, include
from . import views

# the routes will be defined here
urlpatterns = [
    # empty string is root path
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # records
    path('records/', views.records_index, name='index'),
    path('records/<int:record_id>', views.records_details, name='details'),
    path('records/create/', views.RecordCreate.as_view(), name='records_create'),
    path('records/<int:pk>/update/', views.RecordUpdate.as_view(), name='records_update'),
    path('records/<int:pk>/delete/', views.RecordDelete.as_view(), name='records_delete'),

    # add track or artist on record
    path('records/<int:record_id>/add_track/', views.add_track, name='add_track'),
    path('records/<int:record_id>/add_photo/', views.add_photo, name='add_photo'),
    path('records/<int:record_id>/assoc_artist/<int:artist_id>', views.assoc_artist, name='assoc_artist'),

    # artists
    path('artists/', views.ArtistList.as_view(), name='artists_index'),
    path('artists/<int:pk>/', views.ArtistDetail.as_view(), name='artists_detail'),
    path('artists/create/', views.ArtistCreate.as_view(), name='artists_create'),
    path('artists/<int:pk>/update/', views.ArtistUpdate.as_view(), name='artists_update'),
    path('artists/<int:pk>/delete/', views.ArtistDelete.as_view(), name='artists_delete'),

    #auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup')
]

recordcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
        # vv first step, after defined we don't need to touch
    # this file again
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator 
from django.urls import reverse
from main_app.genres import *
from django.contrib.auth.models import User

GENRES = (
    ('ALT', 'Alternative'),
    ('AMB', 'Ambient'),
    ('BLU', 'Blues'),
    ('CLA', 'Classical'),
    ('DIS', 'Disco'),
    ('EMO', 'Emo'),
    ('EXP', 'Experimental'),
    ('FOL', 'Folk'),
    ('FUN', 'Funk'),
    ('HOU', 'House'),
    ('IDT', 'Industrial'),
    ('IND', 'Indie'),
    ('MET', 'Metal'),
    ('PUN', 'Punk'),
    ('RAP', 'Rap'),
    ('REG', 'Reggae'),
    ('SKA', 'Ska'),
    ('SOT', 'Soundtrack'),
    ('SOU', 'Soul'),
    ('TEC', 'Techno'),
)

class Artist(models.Model):
    name = models.CharField('name', max_length=100)
    genre = models.CharField(
        max_length=20,
        choices=GENRES,
        default=GENRES[0][0]
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('artists_detail', kwargs={'pk': self.id})

# Create your models here.
class Record(models.Model):
    name = models.CharField('album name', max_length=100)
    artist = models.CharField(max_length=100)
    cover = models.CharField('Cover Image URL', max_length=200, default='images/record-logo.png')
    num_tracks = models.IntegerField()
    duration = models.IntegerField()
    year = models.IntegerField(validators=[MinValueValidator(1990), MaxValueValidator(2020)])
    artists = models.ManyToManyField(Artist)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name + ' by ' + self.artist

    def get_absolute_url(self):
        return reverse('details', kwargs={'record_id': self.id})


class Track(models.Model):
    title = models.CharField('track title', max_length=100)
    track_num = models.IntegerField('track number')

    record = models.ForeignKey(Record, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.track_num}. {self.title}"
    
    class Meta:
        ordering = ['track_num']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)

    def __str__(self):
      return f"Photo for record_id: {self.record_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Track, Artist
from main_app.genres import *

class TrackForm(ModelForm):
  class Meta:
    model = Track
    fields = ['track_num', 'title']

class ArtistForm(ModelForm):
  class Meta:
    model = Artist
    fields = ['name', 'genre']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Record, Artist
from .forms import TrackForm
from .genres import *
import uuid
import boto3
from .models import Record, Artist, Photo, Track
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'recordcollector'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # How to create a user form object w/browser data
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid credentials - try again'
  # a bad post or get req render signup.html empty
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

# Record Classes and fns

class RecordCreate(LoginRequiredMixin, CreateView):
    model = Record
    fields = '__all__'
    success_url = '/records/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class RecordUpdate(LoginRequiredMixin, UpdateView):
    model = Record
    fields = ['name', 'cover', 'artist', 'year', 'num_tracks']

class RecordDelete(LoginRequiredMixin, DeleteView):
    model = Record
    success_url = '/records/'

# Login required for personalized pages

@login_required
def records_index(request):
    records = Record.objects.filter(user = request.user)
    return render(request, 'records/index.html', {'records': records})

def records_details(request, record_id):
    record = Record.objects.get(id=record_id)
    artists_not_featured = Artist.objects.exclude(id__in = record.artists.all().values_list('id'))
    track_form = TrackForm()
    return render(request, 'records/details.html', {
        'record': record,
        'track_form': track_form,
        'artists': artists_not_featured
    })

@login_required
def add_track(request, record_id):
    form = TrackForm(request.POST)
    if form.is_valid():
        new_track = form.save(commit=False)
        new_track.record_id = record_id
        new_track.save()
    return redirect('details', record_id=record_id)

@login_required
def add_photo(request, record_id):
	# photo-file was the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, record_id=record_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('details', record_id=record_id)

# Artist Classes

class ArtistList(ListView):
    model = Artist

class ArtistDetail(DetailView):
    model = Artist

class ArtistCreate(LoginRequiredMixin, CreateView):
    model = Artist
    genres = GENRES
    fields = '__all__'
    success_url = '/artists/'

class ArtistUpdate(LoginRequiredMixin, UpdateView):
    model = Artist
    fields = '__all__'

class ArtistDelete(LoginRequiredMixin, DeleteView):
    model = Artist
    success_url = '/artists/'

@login_required
def assoc_artist(request, record_id, artist_id):
  # Note that you can pass a toy's id instead of the whole object
  Record.objects.get(id=record_id).artists.add(artist_id)
  return redirect('details', record_id=record_id)

def home(request):
    return render(request, 'about.html')
    
def about(request):
    return render(request, 'about.html')

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h3>Finally, an easy-to use database for store owners</h1>
    <hr />
    <p>This database allows you to research and log
        your personalized collection of records.
    </p>
    <h5><a href="/records">Browse The Database</a></h2>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>RecordDB</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script type = "text/javascript"
        src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>           
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js">
    </script> 
</head>
<body>
    <header class="black navbar-fixed">
        <nav class="black">
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/records" class="left brand-logo"><img src="{% static 'images/record-logo.png' %}"></a></li>
                </ul>
                <ul class="right">
                    <li><a href="/about">About</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'records_create' %}">Add a Record</a></li>
                        <li><a href="/records">View Records</a></li>
                        <li><a href="{% url 'artists_create' %}">Add an Artist</a></li>
                        <li><a href="{% url 'artists_index' %}">View All Artists</a></li>
                        <li><a href="{% url 'logout' %}">Log Out</a></li>
                   {% else %}
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>    
                        <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
            {% if user.is_authenticated %}
    <div>Welcome {{ user }}</div>
    {% endif %}
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="black page-footer">
       <div class="right">All Rights Reserved, &copy; 2019 RecordDB &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/main_app/artist_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Artist</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ artist.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/artist_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Artist Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ artist.name }}</span>
        <p>Genre: {{ artist.genre }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'artists_update' artist.id %}">Edit</a>
        <a href="{% url 'artists_delete' artist.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
<a href="/artists/">Back</a>
{% endblock %}

main_app/templates/main_app/artist_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Artist</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_p }}
    </table>
    <select name="genre">
        <option value="" disabled selected>Choose genre</option>
        {% for genre in genres %}
        <option  value="{{genre}}">{{ genre }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Submit!" class="btn">
</form>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, options);
  });
</script>
{% endblock %}

main_app/templates/main_app/artist_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Artists</h1>

{% for artist in artist_list %}
  <a href="{% url 'artists_detail' artist.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ artist.name }}</span>
            <p>Genre: {{ artist.genre }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/record_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Record</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' record.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/record_form.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/records/details.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ record.name }}</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <img src="{{ record.cover }}" width="80%">
                <p>Artist: {{ record.artist }}</p>
                <p>Tracks: {{ record.num_tracks }}</p>
                {% if record.year >= 2018 %}
                    <p>Year: {{ record.year }} *New Release*</p>
                {% else %}
                    <p>Year: {{ record.year }}</p>
                {% endif %}

                {% if record.duration <= 30 %}
                    <p>Length: {{ record.duration }} min, EP</p>
                {% else %}
                    <p>Length: {{ record.duration }} min, LP</p>
                {% endif %}
            </div>
        </div>
        <div>
            <div class="card-action">
                <a href="{% url 'records_update' record.id%}">Edit</a>
                <a href="{% url 'records_delete' record.id%}">Delete</a>
                <a href="./">Back</a>
            </div>
        </div>
            <!-- Insert photo markup below this comment -->
        {% for photo in record.photo_set.all %}
        <img class="responsive-img materialboxed card-panel" src="{{photo.url}}">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form action="{% url 'add_photo' record.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
        </form>
    </div>
    <!-- new code below -->
    <div class="col s6">
        <!-- new code below -->
        <form method="post" action="{% url 'add_track' record.id %}">
            {% csrf_token %}
            {{ track_form.as_p }}
            <input type="submit" class="btn" value="Add Track">
        </form>
        <table class="striped">
            <thead>
            <tr><th>Track</th><th>Title</th></tr>
            </thead>
            <tbody>
            {% for track in record.track_set.all %}
                <tr>
                <td>{{track.track_num}}</td>
                <td>{{track.title}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Artists on {{ record.name }}</h3>
    {% if record.artists.count %}
      {% for artist in record.artists.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ artist.name }}</span> <br>
            Genre: {{ artist.genre }}
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No associated Artists :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Add Artists</h3>
    <div style="overflow-y: scroll; height:400px;">
    {% if artists.count %}
      {% for artist in artists.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ artist.name }}
                </span><br>
                Genre: {{ artist.genre }}
        </div>
          <div class="card-action">
            <form action="{% url 'assoc_artist' record.id artist.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{record.name}} Has every artist featured</h5>
    {% endif %}
    </div>
    <br>
    Don't see the artist? <a href="/artists/create">Add one here</a>
  </div>
</div>

{% endblock %}

main_app/templates/records/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Record List</h1>

{% for record in records %}
    <div class="card">
        <div class="card-content">
            <a href="{% url 'details' record.id %}">
                <span class="card-title">{{ record.name }}</span>
             </a>
            <p>Artist: {{ record.artist }}</p>
            <p>Tracks: {{ record.num_tracks }}</p>
            {% if record.year >= 2018 %}
                <p>Year: {{ record.year }} *New Release*</p>
            {% else %}
                <p>Year: {{ record.year }}</p>
            {% endif %}

            {% if record.duration <= 30 %}
                <p>Length: {{ record.duration }} min, EP</p>
            {% else %}
                <p>Length: {{ record.duration }} min, LP</p>
            {% endif %}
        </div>
    </div>
{% endfor %}

{% endblock %}